import numpy as np
speaker_id = {
    'zeggs': 0,
    'wayne':1,
    'scott': 2,
    'solomon':3,
    'lawrence': 4,
    'stewart': 5,
    'carla': 6,
    'sophie': 7,
    'catherine':8,
    'miranda': 9,
    'kieks': 10,
    'nidal': 11,
    'zhao': 12,
    'lu': 13,
    'zhang':14,
    'carlos': 15,
    'jorge': 16,
    'itoi': 17,
    'daiki': 18,
    'jaime':19,
    'li': 20,
    'ayana': 21,
    'luqi': 22,
    'hailing': 23,
    'kexin': 24,
    'goto': 25,
    'reamey':26,
    'yingqing': 27,
    'tiffnay': 28,
    'hanieh':29,
    'katya':30,
}


